version: '3'

networks:
    filmcom-ticketing-network:

volumes:
    mysql_data:
        driver: local
    redis_data:
        driver: local

services:
    filmcom:
        build: .
        networks:
            - filmcom-ticketing-network
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - redis
        environment:
            DB_HOST: mysql
            REDIS_HOST: mysql
        restart: always

    api:
        extends:
            service: filmcom
        ports:
            - "9098:9000"
        command: php artisan octane:start --host=0.0.0.0 --port=9000 --server=swoole

    worker:
        extends:
            service: filmcom
        command: php artisan horizon

    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        networks:
            - filmcom-ticketing-network
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: filmcom-ticketing
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis
        networks:
            - filmcom-ticketing-network
        restart: always
        ports:
            - 6380:6379
        volumes:
            - redis_data:/data

    locust_base:
        build:
            context: ./locust
        environment:
            FILE_NAME: film_picking/film_scrolling_simulation_load_test.py
        working_dir: /mnt/locust
        restart: always
        networks:
            - filmcom-ticketing-network
        volumes:
            - ./locust:/mnt/locust

    locust_master:
        extends:
            service: locust_base
        ports:
            - "8089:8089"
        command:
            - -f
            - /mnt/locust/locustfile.py
            - --master
            - --host=http://api:9000
            - --users=100
            - --spawn-rate=1

    locust_worker:
        extends:
            service: locust_base
        depends_on:
            - locust_master
        deploy:
            replicas: 4
        command: -f /mnt/locust/locustfile.py --worker --master-host locust_master

#    locust_worker_picking:
#        extends:
#            service: locust_worker
#        command: -f /mnt/locust/film_picking/film_scrolling_simulation_load_test.py --worker --master-host locust_master
#
#    locust_worker_creating:
#        extends:
#            service: locust_worker
#        command: -f /mnt/locust/film_creation/film_creation_load_test.py --worker --master-host locust_master
