FROM ekyidag/filmcom-ticketing

RUN apt-get update && apt-get install -y cron

RUN echo "* * * * * root cd /var/www/html && /usr/local/bin/php artisan schedule:run > /proc/1/fd/1 2>/proc/1/fd/2" >> /etc/cron.d/filmcom-scheduler

RUN chmod 0644 /etc/cron.d/filmcom-scheduler

RUN touch /var/log/cron.log

CMD cron -f -L 15 2>&1 | tee /var/log/cron.log

