name: Laravel PHP Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare Laravel environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Copy sample_seat_map.xlsx
        run: |
          mkdir -p storage/app
          cp ./storage/app/sample_seat_map.xlsx storage/app/sample_seat_map.xlsx

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: root
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: php artisan test tests/Feature

      - name: Build Docker image
        run: |
          COMMIT_TAG=$(git rev-parse --short HEAD) docker build . -t ekyidag/filmcom-ticketing:$COMMIT_TAG
